log_level: info
servers:
  - listen: 8084
    protocol: http
    routes:
      - matcher:
          prefix: /
          prefix_rewrite: /
        forward_to: http://192.168.0.0:9393
        methods:
          - POST
