log_level: trace
servers:
  - listen: 8443
    protocol: https
    domains:
      - www.937453.xyz
    routes:
      - matchers:
          - kind: path
            value: /api/v1
        forward_to:
          kind: random
          targets:
            - endpoint: http://192.168.0.1:8888/
            - endpoint: http://192.168.0.2:9987/
      - matchers:
          - kind: path
            value: /api/v1
        forward_to:
          kind: random
          targets:
            - endpoint: https://192.168.0.3:443/
