log_level: info
servers:
  - listen: 4486
    protocol: http
    routes:
      - matcher:
          prefix: /
          prefix_rewrite: /
        forward_to:
          kind: random
          targets:
            - endpoint: http://localhost:6666/
        health_check:
          kind: http_get
          base_health_check_param:
            timeout: 10
            interval: 10
          path: /health
        liveness_config:
          min_liveness_count: 1
