servers:
  - listen: 8084
    protocol: http
    routes:
      - matchers:
          - kind: path
            value: /api/v1
        forward_to:
          kind: weight
          targets:
            - endpoint: https://httpbin.org/get
              weight: 1
        middlewares:
          - kind: cors
            allowed_origins:
              - http://127.0.0.1
            allowed_methods:
              - PUT
              - GET
            allowed_headers: "*"
            allow_credentials: true
            max_age: 3600
            options_passthrough: true
