log_level: debug
servers:
  - listen: 8084
    protocol: http
    routes:
      - matchers:
          - kind: path
            value: /api/v1
          - kind: host
            value: 127.0.0.1:8084
          - kind: header
            name: ss
            value: X-Forwarded-For
          - kind: method
            values:
              - GET
              - POST
        timeout:
          request_timeout: 3000
        forward_to: http://192.168.0.0:9393
